-- Create server_names table
CREATE TABLE IF NOT EXISTS public.server_names (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_server_names_server_id ON public.server_names(server_id);

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_server_names_updated_at
    BEFORE UPDATE ON public.server_names
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column(); 